fix(audio-player): better error messages
There was a bug in my code where my stream url was null and I was getting a cryptic error message:
```
TypeError: Cannot read property 'startsWith' of null

     at AudioPlayer.<anonymous> (node_modules/virtual-alexa/lib/src/audioPlayer/AudioPlayer.js:233:46)
     at step (node_modules/virtual-alexa/lib/src/audioPlayer/AudioPlayer.js:32:23)
     at Object.next (node_modules/virtual-alexa/lib/src/audioPlayer/AudioPlayer.js:13:53)
     at node_modules/virtual-alexa/lib/src/audioPlayer/AudioPlayer.js:7:71
     at Object.<anonymous>.__awaiter (node_modules/virtual-alexa/lib/src/audioPlayer/AudioPlayer.js:3:12)
     at AudioPlayer.Object.<anonymous>.AudioPlayer.playNext (node_modules/virtual-alexa/lib/src/audioPlayer/AudioPlayer.js:227:16)
     at AudioPlayer.<anonymous> (node_modules/virtual-alexa/lib/src/audioPlayer/AudioPlayer.js:183:41)
     at step (node_modules/virtual-alexa/lib/src/audioPlayer/AudioPlayer.js:32:23)
     at Object.next (node_modules/virtual-alexa/lib/src/audioPlayer/AudioPlayer.js:13:53)
```
I wasn't sure which paramter it was complaining about, so I had to look at the source code in `AudioPlayer.ts`.

This small check should return a more descriptive error message and let the developer know that it is the stream URL that is the problem.